version: '3.4'

services:

    # Angular Web Application "Infotecs Magazine"
    magazine.web:
        image: ${DOCKER_REGISTRY-}magazine-web-image
        container_name: magazine-web-container
        restart: always
        depends_on:
            - magazine.api
            - infotecs.identity
        ports:
            - 5498:5498    # ssl    https://localhost:5498

    # Web API "Infotecs Magazine API"
    magazine.api:
        image: ${DOCKER_REGISTRY-}magazine-api-image
        container_name: magazine-api-container
        restart: always
        environment:
            - ASPNETCORE_ENVIRONMENT=Production
            - ASPNETCORE_URLS=http://*:5080
        depends_on:
            - magazine.db
        extra_hosts:
            - "localhost:172.17.0.1"

    # PostgreSQL Database "Infotecs Magazine Database"
    magazine.db:
        image: postgres
        container_name: magazine-db-container
        restart: always
        environment:
            - POSTGRES_PASSWORD=1
        ports:
            - 5436:5432

      # MVC Application "Infotecs Identity"
    infotecs.identity:
        image: ${DOCKER_REGISTRY-}infotecs-identity-image
        container_name: infotecs-identity-container
        restart: always
        environment:
            - ASPNETCORE_ENVIRONMENT=Production
            - ASPNETCORE_URLS=https://*:5082
            - ASPNETCORE_Kestrel__Certificates__Default__Password=password
            - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/localhost.pfx
        volumes:
            - ~/.aspnet/https:/https:ro
        ports:
            - 5082:5082
