version: '3.4'

services:

    # Angular Web Application "Infotecs Magazine"
    magazine.web:
        image: ${DOCKER_REGISTRY-}magazine-web-image
        container_name: magazine-web-container
        restart: always
        build:
            context: ./Source/Magazine.Web
            dockerfile: Dockerfile
        depends_on:
            - magazine.api
            - infotecs.identity
        ports:
            - 5498:8080    #        http://localhost:5498
            - 5690:8094    # ssl    https://localhost:5690

    # Web API "Infotecs Magazine API"
    magazine.api:
        image: ${DOCKER_REGISTRY-}magazine-api-image
        container_name: magazine-api-container
        restart: always
        environment:
            - ASPNETCORE_ENVIRONMENT=Production
            - ASPNETCORE_URLS=http://*:5000
        build:
            context: ./Source
            dockerfile: Magazine.API/Dockerfile
        depends_on:
            - magazine.db
 
    # PostgreSQL Database "Infotecs Magazine Database"
    magazine.db:
        image: postgres
        container_name: magazine-db-container
        restart: always
        environment:
            - POSTGRES_PASSWORD=1        
        ports:
            - 5436:5432

      # MVC Application "Infotecs Identity"
    infotecs.identity:
        image: ${DOCKER_REGISTRY-}infotecs-identity-image
        container_name: infotecs-identity-container
        restart: always
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - ASPNETCORE_URLS=http://*:5082
        build:
            context: ./Source
            dockerfile: Magazine.Identity/Dockerfile
        ports:
            - 5084:5082
