version: '3.4'

services:
    magazine.web:
        image: ${DOCKER_REGISTRY-}magazine-web-image
        container_name: magazine-web-container
        build:
            context: ./Source
            dockerfile: Magazine.Web/Dockerfile
        ports:
        - "63585:8000"
    magazine.api:
        image: ${DOCKER_REGISTRY-}magazine-api-image
        container_name: magazine-api-container
        build:
            context: ./Source
            dockerfile: Magazine.API/Dockerfile
        ports:
            - "63588:5000"
    magazine.db:
        image: ${DOCKER_REGISTRY-}magazine-db-image
        container_name: magazine-db-container
        build:
            context: ./Database
            dockerfile: Dockerfile
        ports:
            - "5436:5432"
