DROP TABLE IF EXISTS public.Comment;
DROP TABLE IF EXISTS public.Article;
DROP TABLE IF EXISTS public.User;

CREATE TABLE public.User
(
	Id INT GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,
	CONSTRAINT PK_User PRIMARY KEY (Id),
	Login VARCHAR(320) NOT NULL,
	CONSTRAINT UNQ_User_Login UNIQUE (Login),
	Password CHAR(64) NOT NULL,
	Salt CHAR(24) NOT NULL
);

CREATE TABLE public.Article
(
	Id INT GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,
	CONSTRAINT PK_Article PRIMARY KEY (Id),
	Title VARCHAR(80) NOT NULL,
	CONSTRAINT UNQ_Article_Title UNIQUE (Title),
	Teaser BYTEA NULL,
	Body VARCHAR(60000) NOT NULL,
	CONSTRAINT CHK_Article_Body CHECK (LENGTH(Body) >= 2000),
	UserId INT NOT NULL,
	CONSTRAINT FK_Article_UserId_User_Id FOREIGN KEY (UserId) REFERENCES public.User (Id)
);

CREATE TABLE public.Comment
(
	Id INT GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,
	CONSTRAINT PK_Comment PRIMARY KEY (Id),
	Body VARCHAR(6000) NOT NULL,
	CONSTRAINT CHK_Comment_Body CHECK (LENGTH(TRIM(Body)) > 0),
	ArticleId INT NOT NULL,
	CONSTRAINT FK_Comment_ArticleId_Article_Id FOREIGN KEY (ArticleId) REFERENCES public.Article (Id),
	UserId INT NOT NULL,
	CONSTRAINT FK_Comment_UserId_User_Id FOREIGN KEY (UserId) REFERENCES public.User (Id)
);