// <auto-generated />
using System;
using Magazine.Infrastracture.DB;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace Infotecs.Magazine.Infrastracture.DB.Migrations
{
    [DbContext(typeof(Context))]
    partial class ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("Magazine.Domain.Entities.Account", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("INT")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityAlwaysColumn);

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnName("login")
                        .HasColumnType("VARCHAR(320)")
                        .HasMaxLength(320);

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnName("password")
                        .HasColumnType("CHAR(64)")
                        .IsFixedLength(true)
                        .HasMaxLength(64);

                    b.Property<string>("Salt")
                        .IsRequired()
                        .HasColumnName("salt")
                        .HasColumnType("CHAR(24)")
                        .IsFixedLength(true)
                        .HasMaxLength(24);

                    b.HasKey("Id")
                        .HasName("pk_account");

                    b.HasIndex("Login")
                        .IsUnique()
                        .HasName("unq_account_login");

                    b.ToTable("account");
                });

            modelBuilder.Entity("Magazine.Domain.Entities.Article", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("INT")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityAlwaysColumn);

                    b.Property<int>("AccountId")
                        .HasColumnName("accountid")
                        .HasColumnType("INT");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnName("body")
                        .HasColumnType("VARCHAR(60000)")
                        .HasMaxLength(60000);

                    b.Property<byte[]>("Teaser")
                        .HasColumnName("teaser")
                        .HasColumnType("BYTEA");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnName("title")
                        .HasColumnType("VARCHAR(80)")
                        .HasMaxLength(80);

                    b.HasKey("Id")
                        .HasName("pk_article");

                    b.HasIndex("AccountId");

                    b.HasIndex("Title")
                        .IsUnique()
                        .HasName("unq_article_title");

                    b.ToTable("article");

                    b.HasCheckConstraint("chk_article_body", "LENGTH(body) >= 2000");
                });

            modelBuilder.Entity("Magazine.Domain.Entities.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("INT")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityAlwaysColumn);

                    b.Property<int>("AccountId")
                        .HasColumnName("accountid")
                        .HasColumnType("INT");

                    b.Property<int>("ArticleId")
                        .HasColumnName("articleid")
                        .HasColumnType("INT");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnName("body")
                        .HasColumnType("VARCHAR(6000)")
                        .HasMaxLength(6000);

                    b.HasKey("Id")
                        .HasName("pk_comment");

                    b.HasIndex("AccountId");

                    b.HasIndex("ArticleId");

                    b.ToTable("comment");

                    b.HasCheckConstraint("chk_comment_body", "LENGTH(TRIM(body)) > 0");
                });

            modelBuilder.Entity("Magazine.Domain.Entities.Article", b =>
                {
                    b.HasOne("Magazine.Domain.Entities.Account", "Account")
                        .WithMany("Articles")
                        .HasForeignKey("AccountId")
                        .HasConstraintName("fk_article_accountid_account_id")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("Magazine.Domain.Entities.Comment", b =>
                {
                    b.HasOne("Magazine.Domain.Entities.Account", "Account")
                        .WithMany("Comments")
                        .HasForeignKey("AccountId")
                        .HasConstraintName("fk_comment_accountid_account_id")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Magazine.Domain.Entities.Article", "Article")
                        .WithMany("Comments")
                        .HasForeignKey("ArticleId")
                        .HasConstraintName("fk_comment_articleid_article_id")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
