worker_processes 4;

events { worker_connections 1024; }

http {

    sendfile on;

    # API
    upstream docker-magazine-api {
        server magazine.api:5080;
    }

    # API
    upstream docker-identity {
        server infotecs.identity:5082;
    }

    # Web
    server {
        listen 5498;
        include /etc/nginx/mime.types;

        location / {
            root /var/www/html/;
            try_files $uri $uri/ /index.html;
        }

        location /identity {
			proxy_pass http://docker-identity/identity;
        }

		location /lib/ {
            proxy_pass http://docker-identity/lib/;
		}

		location /css/ {
            proxy_pass http://docker-identity/css/;
		}

		location /icons/ {
            proxy_pass http://docker-identity/icons/;
		}

		location /identity/.well-known/ {
            proxy_pass http://docker-identity/.well-known/;
		}

        location /api {
            proxy_pass         http://docker-magazine-api/api;
            proxy_redirect     off;
            proxy_set_header   Host $host;
            proxy_set_header   X-Real-IP $remote_addr;
            proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header   X-Forwarded-Host $server_name;
        }

        location /default {
            root /var/www/html/;
            try_files $uri $uri/ /index.html;
        }
    }

    # Web SSL
    server {
        listen 5490 ssl;
        include /etc/nginx/mime.types;

        ssl_certificate      /etc/ssl/certs/certificate.pem;
        ssl_certificate_key  /etc/ssl/certs/certificate.key;

        ssl_session_cache    shared:SSL:1m;
        ssl_session_timeout  5m;

        ssl_ciphers  HIGH:!aNULL:!MD5;
        ssl_prefer_server_ciphers  on;

        location / {
            root /var/www/html/;
            try_files $uri $uri/ /index.html;
        }

        location /identity {
            proxy_pass http://docker-identity/identity;
        }

		location /lib/ {
            proxy_pass http://docker-identity/lib/;
		}

		location /css/ {
            proxy_pass http://docker-identity/css/;
		}

		location /icons/ {
            proxy_pass http://docker-identity/icons/;
		}

		location /identity/.well-known/ {
            proxy_pass http://docker-identity/.well-known/;
		}

        location /api {
            proxy_pass         http://docker-magazine-api/api;
            proxy_redirect     off;
            proxy_set_header   Host $host;
            proxy_set_header   X-Real-IP $remote_addr;
            proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header   X-Forwarded-Host $server_name;
        }

        location /default {
            root /var/www/html/;
            try_files $uri $uri/ /index.html;
        }
    }
}
